### PR TITLE
Milestone 5: Full website

### PR DESCRIPTION
**Pull request by AkashaRojee**
Hello!

I built the full website.

Things done:

- Set up routing with React Router
  - Create route for each page (Home, Calculator, Quote)
  - Set basename
- Create components based on identified hierarchy for full website
```
- Header
  - WebsiteTitle
  - NavigationBar
- Route: Home
  - PageHeading
  - TextBody
- Route: Calculator
  - Display
  - Keyboard
    - Key(s)
- Route: Quote
  - TextBody
```
- Add styling with React basic styling
- Refactor code
- Fix linter errors
- Update build for deploy
- Update README

Please, review the code.

Thanks!

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] Please follow the design of the calculator as given in the project requirements. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by AkashaRojee** [comment]
Hi @arslanbisharat,

Thanks for the review.

However, the project requirements specify to add our own styles to improve the look and feel.

Based on the design I went with for the website, I modified the design of the calculator accordingly.

**Comment by arslanbisharat** [comment]
> Hi @arslanbisharat,
> 
> Thanks for the review.
> 
> However, the project requirements specify to add our own styles to improve the look and feel.
> 
> Based on the design I went with for the website, I modified the design of the calculator accordingly.

Yes that is about the whole design not calculator. You can customize anything else but Calculator.

**Comment by AkashaRojee** [comment]
Hi @arslanbisharat,

Thanks for the reply.

The design of the calculator itself is not part of the project requirements for this milestone.

**Comment by arslanbisharat** [comment]
> Hi @arslanbisharat,
> 
> Thanks for the reply.
> 
> The design of the calculator itself is not part of the project requirements for this milestone.

Yes you are right but you see it was a part of requirement on milestone "Components".

**Comment by AkashaRojee** [comment]
Hi @arslanbisharat,

This pull request is for the milestone "Full website", and not for the milestone "Components".

For the milestone "Components", the calculator was styled accordingly.

The project requirements for the milestone "Full website" specify to add our own styles to improve the look and feel - which is what's been done here.

**Comment by arslanbisharat** [comment]
> Hi @arslanbisharat,
> 
> This pull request is for the milestone "Full websites", and not for the milestone "Components".
> 
> For the milestone "Components", the calculator was styled accordingly.
> 
> The project requirements for the milestone "Full websites" specify to add our own styles to improve the look and feel - which is what's been done here.

Each milestone is a type of stair to lead us towards our main goal. The design you are saying is about the full website not calculator. Please make the changes as requested. 
In case you are not satisfied by my review please submit the form for second opinion

**Comment by AkashaRojee** [comment]
@arslanbisharat 

Each milestone is a step towards the final milestone, but this current milestone specifically says to add our own styles to improve the look and feel.

It does not say to add styles to match the original calculator design.

Adding our own styles requires restyling the components to match the chosen look and feel.

A second opinion request has been submitted.

**Review by SpaYco — COMMENTED** [review]
Hello 👋,

_This is an additional review as a result of the second opinion request._

Since the calculator design is outside of the project scope, it's okay to customize it!

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

**Comment by AkashaRojee** [comment]
Hello @SpaYco,

Thanks!

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by AkashaRojee** [comment]
Hi @arslanbisharat,

Thanks!

**Pull request closed without merging**
